"""initial schema

Revision ID: 239688c9b228
Revises: 
Create Date: 2025-12-29 19:12:35.084956+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "239688c9b228"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column(
            "role",
            sa.Enum(
                "BUYER", "SELLER", "ADMIN", name="user_role", create_constraint=True
            ),
            nullable=False,
        ),
        sa.Column("email_verified", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=True),
        sa.Column("last_name", sa.String(length=100), nullable=True),
        sa.Column("avatar_url", sa.Text(), nullable=True),
        sa.Column(
            "oauth_provider",
            sa.Enum(
                "GOOGLE",
                "FACEBOOK",
                "GITHUB",
                name="oauth_provider",
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column("oauth_provider_id", sa.String(length=255), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(
        "ix_users_oauth", "users", ["oauth_provider", "oauth_provider_id"], unique=False
    )
    op.create_index(
        "ix_users_role_active", "users", ["role", "is_active"], unique=False
    )
    op.create_table(
        "books",
        sa.Column("seller_id", sa.UUID(), nullable=False),
        sa.Column("isbn", sa.String(length=20), nullable=True),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("author", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "condition",
            sa.Enum(
                "NEW",
                "LIKE_NEW",
                "GOOD",
                "ACCEPTABLE",
                name="book_condition",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("price", sa.DECIMAL(precision=10, scale=2), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("images", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "ACTIVE",
                "SOLD",
                "ARCHIVED",
                name="book_status",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("category", sa.String(length=100), nullable=True),
        sa.Column("publisher", sa.String(length=255), nullable=True),
        sa.Column("publication_year", sa.Integer(), nullable=True),
        sa.Column("language", sa.String(length=50), nullable=False),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["seller_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_books_category"), "books", ["category"], unique=False)
    op.create_index(
        "ix_books_category_status", "books", ["category", "status"], unique=False
    )
    op.create_index(op.f("ix_books_isbn"), "books", ["isbn"], unique=False)
    op.create_index("ix_books_price_status", "books", ["price", "status"], unique=False)
    op.create_index(op.f("ix_books_seller_id"), "books", ["seller_id"], unique=False)
    op.create_index(
        "ix_books_seller_status", "books", ["seller_id", "status"], unique=False
    )
    op.create_index(op.f("ix_books_status"), "books", ["status"], unique=False)
    op.create_index(
        "ix_books_status_created", "books", ["status", "created_at"], unique=False
    )
    op.create_table(
        "orders",
        sa.Column("buyer_id", sa.UUID(), nullable=False),
        sa.Column("total_amount", sa.DECIMAL(precision=10, scale=2), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "PAYMENT_PROCESSING",
                "PAID",
                "SHIPPED",
                "DELIVERED",
                "CANCELLED",
                "REFUNDED",
                name="order_status",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("stripe_payment_id", sa.String(length=255), nullable=True),
        sa.Column("stripe_session_id", sa.String(length=255), nullable=True),
        sa.Column("shipping_address", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["buyer_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("stripe_payment_id"),
        sa.UniqueConstraint("stripe_session_id"),
    )
    op.create_index(op.f("ix_orders_buyer_id"), "orders", ["buyer_id"], unique=False)
    op.create_index(
        "ix_orders_buyer_status", "orders", ["buyer_id", "status"], unique=False
    )
    op.create_index(op.f("ix_orders_status"), "orders", ["status"], unique=False)
    op.create_index(
        "ix_orders_status_created", "orders", ["status", "created_at"], unique=False
    )
    op.create_table(
        "messages",
        sa.Column("sender_id", sa.UUID(), nullable=False),
        sa.Column("recipient_id", sa.UUID(), nullable=False),
        sa.Column("book_id", sa.UUID(), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["book_id"], ["books.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["recipient_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["sender_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_messages_book_created", "messages", ["book_id", "created_at"], unique=False
    )
    op.create_index(op.f("ix_messages_book_id"), "messages", ["book_id"], unique=False)
    op.create_index(
        "ix_messages_conversation",
        "messages",
        ["sender_id", "recipient_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_messages_recipient_id"), "messages", ["recipient_id"], unique=False
    )
    op.create_index(
        "ix_messages_recipient_unread",
        "messages",
        ["recipient_id", "read_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_messages_sender_id"), "messages", ["sender_id"], unique=False
    )
    op.create_table(
        "order_items",
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("book_id", sa.UUID(), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column(
            "price_at_purchase", sa.DECIMAL(precision=10, scale=2), nullable=False
        ),
        sa.Column("book_title", sa.String(length=500), nullable=False),
        sa.Column("book_author", sa.String(length=255), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["book_id"], ["books.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_order_items_book_id"), "order_items", ["book_id"], unique=False
    )
    op.create_index(
        "ix_order_items_order_book",
        "order_items",
        ["order_id", "book_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_order_items_order_id"), "order_items", ["order_id"], unique=False
    )
    op.create_table(
        "reviews",
        sa.Column("book_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("is_verified_purchase", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "rating >= 1 AND rating <= 5", name="ck_review_rating_range"
        ),
        sa.ForeignKeyConstraint(["book_id"], ["books.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("book_id", "user_id", name="uq_review_book_user"),
    )
    op.create_index(op.f("ix_reviews_book_id"), "reviews", ["book_id"], unique=False)
    op.create_index(
        "ix_reviews_book_rating", "reviews", ["book_id", "rating"], unique=False
    )
    op.create_index(op.f("ix_reviews_user_id"), "reviews", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_reviews_user_id"), table_name="reviews")
    op.drop_index("ix_reviews_book_rating", table_name="reviews")
    op.drop_index(op.f("ix_reviews_book_id"), table_name="reviews")
    op.drop_table("reviews")
    op.drop_index(op.f("ix_order_items_order_id"), table_name="order_items")
    op.drop_index("ix_order_items_order_book", table_name="order_items")
    op.drop_index(op.f("ix_order_items_book_id"), table_name="order_items")
    op.drop_table("order_items")
    op.drop_index(op.f("ix_messages_sender_id"), table_name="messages")
    op.drop_index("ix_messages_recipient_unread", table_name="messages")
    op.drop_index(op.f("ix_messages_recipient_id"), table_name="messages")
    op.drop_index("ix_messages_conversation", table_name="messages")
    op.drop_index(op.f("ix_messages_book_id"), table_name="messages")
    op.drop_index("ix_messages_book_created", table_name="messages")
    op.drop_table("messages")
    op.drop_index("ix_orders_status_created", table_name="orders")
    op.drop_index(op.f("ix_orders_status"), table_name="orders")
    op.drop_index("ix_orders_buyer_status", table_name="orders")
    op.drop_index(op.f("ix_orders_buyer_id"), table_name="orders")
    op.drop_table("orders")
    op.drop_index("ix_books_status_created", table_name="books")
    op.drop_index(op.f("ix_books_status"), table_name="books")
    op.drop_index("ix_books_seller_status", table_name="books")
    op.drop_index(op.f("ix_books_seller_id"), table_name="books")
    op.drop_index("ix_books_price_status", table_name="books")
    op.drop_index(op.f("ix_books_isbn"), table_name="books")
    op.drop_index("ix_books_category_status", table_name="books")
    op.drop_index(op.f("ix_books_category"), table_name="books")
    op.drop_table("books")
    op.drop_index("ix_users_role_active", table_name="users")
    op.drop_index("ix_users_oauth", table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
